[package]
name = "braidwork-project"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
braidwork-core = { path = "../braidwork-core" }
uuid.workspace = true
braidwork-store = { path = "../braidwork-store" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
rusqlite.workspace = true
tempfile.workspace = true

[lints]
workspace = true
